# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages

baseurl: "/psci8357"

exclude: ["*.rmd"]

markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""  # All files
    values:
      layout: default
